# alpha_siat/models/__init__.py
from . import res_company
from . import siat_config
from . import siat_client
from . import siat_cuis
from . import siat_cufd
from . import siat_actividad
from . import siat_actividad_documento_sector
from . import siat_mensaje_servicio
from . import siat_producto_servicio
from . import siat_leyenda
from . import siat_evento_significativo
from . import siat_motivo_anulacion
from . import siat_pais_origen
from . import siat_tipo_documento_identidad
from . import siat_tipo_habitacion
from . import siat_tipo_metodo_pago
from . import siat_tipo_moneda
from . import siat_tipo_punto_venta
from . import siat_tipos_factura
from . import siat_unidad_medida
from . import siat_tipo_documento_sector
from . import siat_tipo_emision
from . import product_template
from . import res_partner
from . import siat_cuf_generator
from . import pos_order
from . import account_move
from . import purchase_invoice
from . import account_move_pdf