{
    'name': 'Accounting Community',
    'license': 'LGPL-3',
    'version': '18.0.1.0.0',
    'author': 'Alpha Systems S.R.L.',
    'website': 'https://www.alphasys.com.bo',
    'category': 'Accounting/Accounting',
    'depends': [
        'base',
        'account',
        'purchase',
        'hr_expense',
        'report_xlsx',
        'alpha_siat',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/bankbook_wizard_view.xml',
        'views/banking_wizard_view.xml',
        'views/iva_wizard_view.xml',
        'views/account_payment_view.xml',
        'reports/bankbook_actions.xml',
        'reports/banking_report_actions.xml',
        'reports/iva_report_actions.xml',
        'reports/accountentry_report.xml',
        'reports/accountentry_report_templates.xml',
        'reports/accountentry_second.xml',
        'reports/accountentry_second_templates.xml',
        'reports/accountentry_much.xml',
        'reports/accountentry_much_templates.xml',
        'reports/accountentry_migracion.xml',
        'reports/accountentry_migracion_templates.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'accounting_community/static/src/js/action_manager.js',
        ],
    },
    'installable': True,
}
