{
    "name": "Alpha SIAT - Bolivia Electronic Invoicing - Reha",
    "version": "18.1",
    "author": "ALPHA SYSTEMS",
    "license": "LGPL-3",
    "category": "Accounting/Localizations",
    "summary": "Base Configuration for Bolivia SIAT Electronic Invoicing",
    "depends": ["base", "account","product","stock", "point_of_sale"],
    "data": [
        "security/ir.model.access.csv",
        "views/siat_config_views.xml",
        "views/siat_cuis_views.xml",
        "views/res_company_view.xml",
        'views/siat_cufd_views.xml',  # Add this
        'views/siat_actividad_views.xml',
        'views/siat_actividad_documento_sector_views.xml',
        'views/siat_mensaje_servicio_views.xml',
        'views/siat_leyenda_views.xml',
        'views/siat_evento_significativo_views.xml',
        'views/siat_motivo_anulacion_views.xml',
        'views/siat_pais_origen_views.xml',
        'views/siat_tipo_documento_identidad_views.xml',
        'views/siat_tipo_habitacion_views.xml',
        'views/siat_tipo_metodo_pago_views.xml',
        'views/siat_tipo_moneda_views.xml',
        'views/siat_tipo_punto_venta_views.xml',
        'views/siat_tipos_factura_views.xml',
        'views/siat_unidad_medida_views.xml',
        'views/siat_tipo_documento_sector_views.xml',
        'views/siat_tipo_emision_views.xml',
        'views/product_template_siat_views.xml',
        'views/res_partner_views.xml',
        'views/pos_order_views.xml',
        'views/purchase_invoice_views.xml',
        'views/account_move_views.xml',
        #'views/account_move_anulacion_views.xml'
        # 'data/ir_cron_data.xml',  # Add this
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
